{% set name = "gds-lowlatency-tools" %}
{% set version = "2.19.6" %}

# dependencies
{% set gds_base_version = "2.19.8" %}
{% set gds_lsmp_version = "2.19.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 0b37336c2ce909999138296033ea72249128e07dd9b2001980337a141e5e372b
  patches:
    - dpush-vstream-macos.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - gds-base >={{ gds_base_version }}
    - gds-framexmit >={{ gds_base_version }}
    - gds-lsmp >={{ gds_lsmp_version }}
  run:
    - gds-base >={{ gds_base_version }}
    - gds-framexmit >={{ gds_base_version }}
    - gds-lsmp >={{ gds_lsmp_version }}

test:
  commands:
    - DpushM --help
    - DpushRT --help
    - DpushTease --help
    - framelink --help
    - fxpktdump --help

about:
  home: https://computing.docs.ligo.org/daswgweb/projects/dmt.html
  dev_url: https://git.ligo.org/gds/gds.git
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: GDS Utilities low-latency libraries
  description: |
    GDS Utilities low latency data distribution sub-system libraries and
    utilities.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
